--- #YAML:1.0
name:               MIME-Lite-HT-HTML
version:            0.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime::Format::Mail:  >= 0.3001
    Encode:               0
    HTML::FormatText:     >= 2.04
    HTML::FormatText::WithLinks:  >= 0.11
    HTML::Template:       >= 2.9
    MIME::Lite:           >= 3.027
    MIME::Words:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
