---
name: MIME-Lite-HT-HTML
version: 0.01
author:
  - 'Alexander Becker <c a p f a n _a.t_ g m x . d e>'
abstract: Create html mail with MIME::Lite and HTML::Template
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime::Format::Mail: '>= 0.3001'
  HTML::FormatText: '>= 2.04'
  HTML::FormatText::WithLinks: '>= 0.11'
  HTML::Template: '>= 2.9'
  MIME::Lite: '>= 3.027'
configure_requires:
  Module::Build: 0.340201
provides:
  MIME::Lite::HT::HTML:
    file: lib/MIME/Lite/HT/HTML.pm
    version: 0.01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
