---
abstract: 'Create HTML mail with MIME::Lite and HTML::Template'
author:
  - 'Alexander Becker <c a p f a n ^at^ g m x -dot- d e>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.98'
  Test::Pod: '1.0'
  Test::Pod::Coverage: '1.08'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIME-Lite-HT-HTML
no_index:
  directory:
    - t
    - inc
requires:
  DateTime::Format::Mail: '0.3001'
  Encode: '0'
  ExtUtils::MakeMaker: '6.98'
  HTML::FormatText: '2.04'
  HTML::FormatText::WithLinks: '0.11'
  HTML::Template: '2.9'
  MIME::Lite: '3.027'
  MIME::Words: '0'
  perl: '5.006001'
resources:
  repository: https://github.com/asb-capfan/MIME-Lite-HT-HTML
version: '0.05'
